steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/farmcare-backend:$COMMIT_SHA',
      '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/farmcare-backend:latest',
      '.'
    ]
  
  # 2. Push the Docker images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/farmcare-backend:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/farmcare-backend:latest']
    
  # 3. Deploy container image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'farmcare-backend'
      - '--image'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/farmcare-backend:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/farmcare-backend:$COMMIT_SHA'
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/farmcare-backend:latest'
